In [2]:
import tensorflow as tf

In [3]:
tensor1 = tf.constant(3.7, dtype=tf.float32)
tensor1

2022-01-21 18:04:36.275519: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-01-21 18:04:36.275947: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-01-21 18:04:36.280150: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


<tf.Tensor: shape=(), dtype=float32, numpy=3.7>

In [4]:
tensor1 = tf.constant(value=3.7, dtype=tf.float32)
tensor2 = tf.constant(value=[[0.5], [7]], dtype=tf.float32)
tensor3 = tf.constant(value=[[12, 9]], dtype=tf.float32)
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(3.7, shape=(), dtype=float32)
tf.Tensor(
[[0.5]
 [7. ]], shape=(2, 1), dtype=float32)
tf.Tensor([[12.  9.]], shape=(1, 2), dtype=float32)


In [8]:
tensor1 = tf.constant(value=3.7, dtype=tf.float32, name="firstConstant")
tensor2 = tf.constant(value=[[0.5], [7]], dtype=tf.float32, name="secondConstant")
tensor3 = tf.constant(value=[[12, 9]], dtype=tf.float32, name="thirdConstant")
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(3.7, shape=(), dtype=float32)
tf.Tensor(
[[0.5]
 [7. ]], shape=(2, 1), dtype=float32)
tf.Tensor([[12.  9.]], shape=(1, 2), dtype=float32)


In [9]:
aa = tf.nn.top_k([1, 2, 3, 4], 2)
print(aa)

TopKV2(values=<tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 3], dtype=int32)>, indices=<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>)
